import {
  BulletList,
  LegalPageShell,
  Lead,
  LineGroup,
  MailLink,
  NoGapLineGroup,
  P,
  PageHeading,
  Section,
  SubSection,
  Article,
} from '@/components/legal/legal-content'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy — Angle HR',
  description: 'How Open HR collects, uses, and protects your personal data.',
}

export default function PrivacyPolicyPage() {
  return (
    <LegalPageShell>
      <Article>
        <div className="flex flex-col gap-16">
          <PageHeading>Privacy Policy</PageHeading>
          <LineGroup
            lines={[
              'Product: Open HR',
              'Operated by: Angle Open Source Ltd',
              'Company number: 17066367',
              'Registered address: 71–75 Shelton Street, London, England, WC2H 9JQ',
              'Effective date: 21 July 2026',
              'Version: 1.0',
            ]}
          />
        </div>

        <Section number={1} title="Who We Are">
          <P>
            Open HR is an HR and hiring platform built for founders and small business operators.
            It&rsquo;s developed and operated by Angle Open Source Ltd, a company registered in
            England and Wales (company number 17066367), based at 71–75 Shelton Street, London,
            England, WC2H 9JQ.
          </P>
          <P>
            We currently operate in the UK, the EU (including Germany), the US, Nigeria, India, and
            Kenya. If you&rsquo;re based somewhere else, please get in touch before creating an
            account, we may not yet have the right setup in place to handle your data properly.
          </P>
          <P>
            For any privacy question, email us at <MailLink />.
          </P>
        </Section>

        <Section number={2} title="What This Policy Covers">
          <P>
            This policy covers personal data we handle through the Open HR website, waitlist,
            account sign-up, and the hosted platform.
          </P>
          <P>
            <Lead>If you&rsquo;re an employee: </Lead> if your employer uses Open HR to manage your
            HR records, we process your data on your employer&rsquo;s behalf, not as an independent
            party. Your employer decides how your data is used and is the one responsible for it. If
            you want to access, correct, or delete your data, please contact your employer directly,
            we support them in handling these requests, but we can&rsquo;t act on them ourselves.
          </P>
        </Section>

        <Section number={3} title="Our Two Roles: Controller and Processor">
          <SubSection number="3.1" title="When we are the data controller">
            <BulletList
              heading="We are the data controller for:"
              items={[
                'Personal data you provide when joining our waitlist (email address, consent record)',
                'Personal data you provide when creating an account (name, email, company details, and for EU business customers, VAT registration details)',
                'Data generated by your use of our website and platform (login logs, session data, usage analytics)',
              ]}
              footer="As controller, we determine the purposes and means of processing and are directly accountable to you and to regulators for that processing."
            />
          </SubSection>

          <SubSection number="3.2" title="When we are the data processor">
            <BulletList
              heading="When you (as an employer) use Open HR to store and manage employee records, applicant data, or team information, you are the data controller and we are the data processor. We process that data only:"
              items={[
                'On your documented instructions',
                'For the purpose of providing the Open HR platform to you',
                'Not for any other commercial purpose of our own, including AI model training, benchmarking, or resale, without your explicit prior written authorisation',
              ]}
              footer="This relationship is governed by our Data Processing Agreement, which you must accept as a mandatory step during account creation. No employee data can be entered into the platform until the DPA is executed."
            />
            <P>
              <Lead>A note on employee consent:</Lead> Across every market we operate in, employee
              consent is not treated as a reliable basis for routine HR processing because of the
              power imbalance in the employment relationship. If you are an employer using Open HR,
              please rely on contractual necessity or legal obligation as your lawful basis for
              standard HR activities (payroll, records, onboarding), rather than asking employees to
              &ldquo;consent&rdquo; to being managed on the platform.
            </P>
          </SubSection>

          <SubSection number="3.3" title="If you are an employee">
            <BulletList
              heading="If your employer uses Open HR and has entered your personal data into the platform, contact your employer directly to:"
              items={[
                'Access a copy of your data',
                'Request corrections or deletions',
                'Exercise any other data subject rights',
              ]}
              footer="Your employer is responsible for responding to your request. We contractually require employers to support employee rights requests and will assist them in doing so, including by providing a full export of the relevant records on request."
            />
          </SubSection>

          <SubSection number="3.4" title="Business (VAT/VIES) data for EU customers">
            <P>
              Where a business customer in the European Union signs up for a paid subscription, we
              may collect and validate a VAT registration number using the EU&rsquo;s VAT
              Information Exchange System (VIES) to determine whether the reverse-charge mechanism
              applies to your invoice. This is processed as part of the contract with you (Art.
              6(1)(b) GDPR) and for compliance with our own EU VAT obligations (Art. 6(1)(c) GDPR).
              VIES validation involves submitting your VAT number to the European Commission&rsquo;s
              VIES service; no other personal data is shared in that exchange. We retain VAT
              validation records for the statutory period required for tax compliance (currently a
              minimum of 6 years, consistent with the retention basis applied to comparable
              financial records).
            </P>
          </SubSection>
        </Section>

        <Section number={4} title="Personal Data We Collect and Why">
          <SubSection number="4.1" title="Joining the waitlist.">
            <P>
              When you join our waitlist, we ask for your name, email address, and country. We use
              this to manage the list and send you an invite when we launch. We collect this simply
              because you&rsquo;ve asked us to, it&rsquo;s necessary to provide the waitlist service
              you&rsquo;re requesting. There&rsquo;s no separate marketing consent checkbox on the
              waitlist form; by submitting the form, you&rsquo;re agreeing to our Terms &amp;
              Conditions, as shown at the point of sign-up. We also briefly collect your IP address
              to prevent spam and bot abuse, which we delete after 30 days. If you don&rsquo;t
              create an account within 90 days of getting your launch invite, we delete your
              waitlist details entirely. If you do create an account, we keep this record for 3
              years.
            </P>
          </SubSection>

          <SubSection number="4.2" title="Creating an account.">
            <P>
              When you sign up, we collect your name, email address, password, company name,
              industry, team size, and country. Your password is hashed and never stored in plain
              text. We use this information to set up your workspace and provide the service, this
              is necessary to fulfil our contract with you. Your country also helps us route you to
              the right legal requirements for your market. If you&rsquo;re an EU business signing
              up for a paid plan, we may also ask for your VAT number, which we check against the
              EU&rsquo;s VIES system so we can invoice you correctly. We keep your account details
              for as long as you have an account, plus 30 days. The exceptions are your DPA
              acceptance record, which we keep for 7 years for legal reasons, and VAT records, kept
              for 6 years for tax purposes.
            </P>
          </SubSection>

          <SubSection number="4.3" title="Using the platform.">
            <P>
              We use short-lived session tokens to keep you logged in, generally for up to 30 days.
              We keep a record of logins for 90 days and failed login attempts for 30 days, both to
              help keep your account secure. Password reset links expire after 15 minutes, and
              invitations to join a workspace as a co-admin expire after 7 days.
            </P>
          </SubSection>

          <SubSection number="4.4" title="Product analytics.">
            <P>
              We collect anonymised or pseudonymised information about how people use Open HR, which
              features get used, where people get stuck during setup, and where errors happen, so we
              can improve the product. We don&rsquo;t build profiles of individual people from this,
              and we don&rsquo;t use it for advertising. If we ever introduce tools that track
              individual behaviour in more detail, such as session recordings, we&rsquo;ll update
              this policy and ask for your consent first.
            </P>
          </SubSection>
        </Section>

        <Section number={5} title="Our Legal Basis for Using Your Data">
          <P>
            Data protection law requires us to have a valid reason for every way we use your
            personal data. In the UK, EU, Nigeria, and Kenya, this generally comes down to one of
            four things: you&rsquo;ve given us consent, we need the data to provide something
            you&rsquo;ve asked for (a contract), we&rsquo;re legally required to collect or keep it
            (a legal obligation), or we have a legitimate business reason that doesn&rsquo;t
            unfairly override your rights (a legitimate interest). The US doesn&rsquo;t require us
            to label a legal basis in the same way, but we only ever use your data for the purposes
            described in this policy.
          </P>
          <P>
            In practice: joining the waitlist and creating an account happen because you&rsquo;ve
            asked us to, so our basis is contract. Security monitoring, fraud prevention, and
            product analytics rely on our legitimate interest in keeping the platform safe and
            useful. Keeping your DPA acceptance record and VAT details is a legal obligation. Any
            marketing emails we send are based on your consent, which you can withdraw at any time
            using the unsubscribe link or by emailing us.
          </P>
          <P>
            If you&rsquo;re an employer processing employee data through Open HR, the basis for that
            processing is yours to determine, but as noted above, please rely on contractual
            necessity or a legal obligation for routine HR tasks rather than employee consent. In
            India, standard HR activities like recruitment, onboarding, payroll, and benefits are
            covered by a specific employment exception in Indian law and don&rsquo;t need separate
            employee consent at all.
          </P>
        </Section>

        <Section number={6} title="Who We Share Data With">
          <NoGapLineGroup
            lines={[
              "We don't sell your personal data, and we don't share it with advertisers.",
              <span key="hosting">
                We use AWS and Cloudflare to host the platform and store data. We also use a
                transactional email provider to send account, verification, and waitlist emails,
                and, for EU users, an EU representative who acts as a point of contact for
                regulators and individuals, as required under EU law when a company isn&rsquo;t
                based in the EU.
              </span>,
              "We'll publish an up-to-date list of everyone we share data with before launch, and we'll tell account holders before adding anyone new who would affect their data, so there's a chance to raise concerns.",
              "If you're a co-admin invited into a workspace, the employer running that workspace can see your name and email, and can manage or remove your access.",
              <span key="disclose">
                We&rsquo;ll disclose personal data to law enforcement, courts, or regulators if
                we&rsquo;re legally required to, and we&rsquo;ll tell you beforehand if we&rsquo;re
                allowed to. If Angle Open Source Ltd is ever acquired or merged with another
                company, personal data may transfer to the new owner, we&rsquo;ll notify you before
                that happens and make sure the new owner is bound by protections at least as strong
                as this policy.
              </span>,
            ]}
          />
        </Section>

        <Section number={7} title="Where We Store Data and International Transfers">
          <NoGapLineGroup
            lines={[
              <span key="hosting-regions">
                We host Open HR on AWS and store data in the region closest to your market wherever
                we can. UK data is stored in the UK. EU data is kept within the EU as a firm
                requirement, not just a preference. US data is stored in the US. For Nigeria, India,
                and Kenya, we don&rsquo;t yet have dedicated in-region hosting, so data from those
                markets is currently stored in the nearest suitable regional infrastructure while we
                finish setting up dedicated hosting, we&rsquo;ll update this policy once
                that&rsquo;s in place.
              </span>,
              <span key="cross-border">
                Whenever data does need to cross borders for example, between our infrastructure and
                a service provider, we put appropriate legal safeguards in place. For the UK and EU,
                this means standard contractual clauses or the UK&rsquo;s equivalent. For Nigeria,
                Kenya, and India, we&rsquo;re finalising the specific mechanisms required under each
                country&rsquo;s law and will publish the details here before we accept a meaningful
                volume of data from those markets.
              </span>,
              "If you're an employer, you and your team may be able to view your workspace data from anywhere you operate, even across borders. This kind of access is covered separately in your Data Processing Agreement with us.",
              <span key="german-works-council">
                <Lead>A note for German employers: </Lead> if your organisation has a works council
                (Betriebsrat), German law requires you to get their agreement before switching on
                any Open HR feature that could be used to monitor employees, things like attendance
                tracking or activity logs. This sits alongside your GDPR obligations, not instead of
                them, and it&rsquo;s something we can&rsquo;t handle on your behalf.
              </span>,
            ]}
          />
        </Section>

        <Section number={8} title="How Long We Keep Your Data">
          <P>
            We only keep personal data for as long as we actually need it. Waitlist details are
            deleted after 90 days if you don&rsquo;t go on to create an account, or kept for 3 years
            if you do. Account information is kept for as long as you have an account, plus 30 days,
            then deleted or anonymised, except your DPA acceptance record (kept 7 years) and VAT
            records for EU business customers (kept 6 years), both for legal reasons. Login and
            security logs are kept on a rolling basis for 30 to 90 days. Password reset links expire
            in 15 minutes, and workspace invitations expire after 7 days. If we ever have a security
            incident, we keep records of it for at least 3 years for regulatory purposes.
          </P>
          <P>
            If we delete something from our main systems, it&rsquo;s also removed from backups
            during our normal backup cycle, until that happens, it isn&rsquo;t considered fully
            deleted under the law.
          </P>
          <P>
            If you&rsquo;re an employer, the retention of your employees&rsquo; records is set out
            in your Data Processing Agreement with us. We recommend keeping employee records for as
            long as someone works for you, plus at least 6 years, then deleting them securely rather
            than archiving them. When your account closes, we delete or return all employee data to
            you, as agreed in the DPA.
          </P>
        </Section>

        <Section number={9} title="Your Rights">
          <NoGapLineGroup
            lines={[
              <span key="general-rights">
                Wherever you&rsquo;re based, you have the right to see a copy of the personal data
                we hold about you, correct anything that&rsquo;s wrong, ask us to delete it (subject
                to anything we&rsquo;re legally required to keep), object to processing based on our
                legitimate interest, and withdraw consent at any time where consent is the basis.
                You can also complain to us directly, or to your local regulator, see Section 15. We
                respond to requests within 30 days; if a request is complex, we may need a further
                30 days (45 days in the US), and we&rsquo;ll let you know if that&rsquo;s the case.
              </span>,
              <span key="exercise-rights">
                To exercise any of these rights, email <MailLink /> and let us know what you&rsquo;d
                like.
              </span>,
              <span key="uk-eu-rights">
                If you&rsquo;re in the UK or EU, you also have the right to ask us to pause
                processing in certain situations, receive your data in a portable format, and be
                told if we&rsquo;ve made any decision about you using automated tools alone, see
                Section 11. In Germany specifically, you can also raise concerns about workplace
                monitoring features with your works council.
              </span>,
            ]}
          />
          <P>
            If you&rsquo;re in the US, you have the right to know what we collect, correct it,
            delete it, and opt out of any sale or sharing of your data, though we don&rsquo;t sell
            or share personal data. We also honour the Global Privacy Control browser signal as a
            valid opt-out. If you&rsquo;re a California-based employee or job applicant of a company
            using Open HR, you have the same rights as any other California resident, the old
            exemption for employee data ended in 2023.
          </P>
          <P>
            If you&rsquo;re in Nigeria, you can ask us to restrict processing, request a portable
            copy of your data where relevant, and object to being subject to a fully automated
            decision.
          </P>
          <P>
            If you&rsquo;re in India, you can access, correct, and erase your data, raise concerns
            with us directly, and nominate someone else to exercise your rights on your behalf if
            something happens to you. India&rsquo;s rights framework is still being rolled out and
            will be complete by May 2027, until then, some requests go through our general process
            rather than a dedicated legal mechanism.
          </P>
          <P>
            If you&rsquo;re in Kenya, you can object to processing, ask for corrections or deletion,
            and request a portable copy of your data. We&rsquo;ll respond within 30 days, or explain
            within 7 days if we&rsquo;re unable to fulfil the request.
          </P>
          <P>
            If you&rsquo;re an employee and your employer has entered your data into Open HR, please
            contact your employer first, they&rsquo;re responsible for your records, and we help
            them respond to you.
          </P>
        </Section>

        <Section number={10} title="Cookies and Tracking">
          <NoGapLineGroup
            lines={[
              'We use cookies on the Open HR website and platform.',
              <span key="cookie-types">
                Some cookies are strictly necessary, they keep you logged in and keep the platform
                secure, and we don&rsquo;t ask for consent to use these. Any cookies used for
                analytics or marketing need your consent first, and you can manage your preferences
                at any time from the cookie settings link in the footer. We don&rsquo;t currently
                use marketing or advertising cookies; if that changes, we&rsquo;ll update this
                notice and ask for your consent.
              </span>,
              <span key="gpc">
                If you visit our website with the Global Privacy Control browser signal turned on,
                we treat that as a valid request to opt out of any sale or sharing of your data. In
                Nigeria, we get your opt-in consent before placing any non-essential cookies, in
                line with local requirements.
              </span>,
            ]}
          />
        </Section>

        <Section number={11} title="Automated Decision-Making">
          <P>
            Open HR&rsquo;s job creation tool includes built-in prompts that flag legal requirements
            based on where a job is posted, for example, reminding an EU employer to disclose a
            salary range, or a Nigerian employer to check their registration status. This helps
            employers meet their own obligations; it doesn&rsquo;t make or influence any decision
            about a candidate or employee under GDPR or similar laws.
          </P>
          <P>
            If we ever build features that use automated tools or AI to screen, rank, or score
            candidates or employees, we&rsquo;ll update this policy first to explain what the tool
            does, what data it uses, what its output means, and how you can ask for a human review.
            Features like that would likely count as high-risk under the EU&rsquo;s AI Act from
            August 2026, and we&rsquo;d put the required safeguards in place before switching them
            on for EU employers.
          </P>
        </Section>

        <Section number={12} title="Security">
          <P>
            We use reasonable technical and organisational measures to protect personal data,
            including encrypting data in transit and at rest, hashing passwords so they&rsquo;re
            never stored in plain text, limiting access to people who need it, logging access to
            sensitive data, and expiring sessions and one-time tokens automatically. If you find a
            security vulnerability in Open HR, please report it to <MailLink />.
          </P>
          <P>
            If a data breach happens, we&rsquo;ll notify the relevant regulators and affected
            individuals in line with our legal obligations, generally within 72 hours in the UK and
            EU, without undue delay in Nigeria and India, and as soon as reasonably possible in
            Kenya. If you&rsquo;re an employer, we&rsquo;ll tell you about any breach affecting your
            workspace within 24 hours, so you have time to meet your own reporting deadlines.
          </P>
        </Section>

        <Section number={13} title="Children's Data">
          <P>
            Open HR is built for business operators and HR professionals, not for children. We
            don&rsquo;t knowingly collect data from anyone under 18. If you think we&rsquo;ve
            accidentally collected data from a child, email <MailLink /> and we&rsquo;ll delete it
            promptly.
          </P>
        </Section>

        <Section number={14} title="Changes to This Policy">
          <NoGapLineGroup
            lines={[
              <span key="changes-intro">
                We update this policy whenever we make a meaningful change to how we handle data,
                for example, adding a new service provider, using data for a new purpose, or
                entering a new market. For meaningful changes, we&rsquo;ll email you at least 14
                days before the change takes effect and show a notice on the platform. For small
                clarifications, we&rsquo;ll just update the date at the top of this page.
              </span>,
              <span key="prior-version">
                You can request an earlier version of this policy at any time by emailing{' '}
                <MailLink />.
              </span>,
            ]}
          />
        </Section>

        <Section number={15} title="Complaints">
          <P>
            If you have a concern about how we&rsquo;ve handled your data, please contact us first
            at <MailLink />. We&rsquo;ll acknowledge your complaint within 5 working days and aim to
            resolve it within 30 days. From 19 June 2026, UK individuals have a legal right to
            complain to us directly before going to the regulator, and we&rsquo;ll follow the same
            30-day acknowledgement window.
          </P>
          <P>
            If we can&rsquo;t resolve things to your satisfaction, you can take your complaint to
            your local regulator. In the UK, that&rsquo;s the Information Commissioner&rsquo;s
            Office (ico.org.uk). In the EU, it&rsquo;s your national data protection authority, you
            can find yours at edpb.europa.eu. In Germany specifically, it&rsquo;s your regional
            Datenschutzbehörde. In Nigeria, it&rsquo;s the Nigeria Data Protection Commission
            (ndpc.gov.ng), you can also use their SNAG process to try to resolve things with us
            first. In India, once its complaints process is fully up and running. In Kenya,
            it&rsquo;s the Office of the Data Protection Commissioner (odpc.go.ke). And if
            you&rsquo;re in California, it&rsquo;s the California Privacy Protection Agency
            (cppa.ca.gov).
          </P>
        </Section>

        <Section number={16} title="How to Contact Us">
          <NoGapLineGroup
            lines={[
              <span key="contact-intro">
                For any privacy question, rights request, or security report, email <MailLink />.
                You can also write to us at Data Protection, Angle Open Source Ltd, 71–75 Shelton
                Street, London, England, WC2H 9JQ.
              </span>,
              <span key="eu-rep">
                We&rsquo;re in the process of appointing an EU representative, as required under EU
                law for a company based outside the EU, we&rsquo;ll publish their contact details
                here once that&rsquo;s confirmed.
              </span>,
              <span key="registration">
                Angle Open Source Ltd is registered in England and Wales, company number 17066367,
                registered office 71–75 Shelton Street, London, England, WC2H 9JQ.
              </span>,
            ]}
          />
        </Section>

        <Section number={17} title="Jurisdiction-Specific Notices">
          <SubSection number="17.1" title="United Kingdom.">
            <P>
              We&rsquo;re the data controller for the processing described in Section 4. We&rsquo;re
              registered in England and Wales, and the applicable law is UK GDPR, the Data
              Protection Act 2018, and the Data (Use and Access) Act 2025. The regulator is the
              Information Commissioner&rsquo;s Office (ico.org.uk). From 19 June 2026, you can
              complain to us directly before the ICO, and we&rsquo;ll acknowledge within 30 days.
              When we transfer data outside the UK, we use approved safeguards to keep it protected
              to UK standards. We&rsquo;re not currently required to have a Data Protection Officer.
            </P>
          </SubSection>

          <SubSection number="17.2" title="European Union, including Germany.">
            <P>
              The applicable law is the EU GDPR. You can complain to your national regulator, find
              yours at edpb.europa.eu. Because we&rsquo;re based in the UK, not the EU, we&rsquo;re
              appointing an EU representative under EU law to act as a point of contact for
              regulators and individuals; we&rsquo;ll publish their details once confirmed. If
              you&rsquo;re an EU business customer, we may validate your VAT number through the
              EU&rsquo;s VIES system for invoicing purposes. If you&rsquo;re a German employer with
              a works council, please see Section 7, they&rsquo;ll need their agreement before
              enabling any monitoring-capable features, separately from your GDPR obligations.
              Employers in France or the Netherlands may face similar works council requirements and
              should check with local counsel before rolling out employee-facing features.
            </P>
          </SubSection>

          <SubSection number="17.3" title="United States.">
            <P>
              We assess our obligations mainly under California&rsquo;s privacy law (CCPA/CPRA),
              given it&rsquo;s the most comprehensive framework among the states. The regulator is
              the California Privacy Protection Agency (cppa.ca.gov). If you&rsquo;re a
              California-based employee or job applicant of a company using Open HR, you have the
              same rights as any other California resident, the old exemption for employee data
              ended in 2023. If your organisation has people in other states with their own privacy
              laws, those may apply too; Texas&rsquo;s law, for example, applies to any business
              serving Texas residents regardless of size. We honour the Global Privacy Control
              signal as a valid opt-out. As an employer, you remain responsible for your own
              compliance with US employment law, including any state rules on automated hiring
              tools.
            </P>
          </SubSection>

          <SubSection number="17.4" title="Nigeria.">
            <P>
              The applicable law is the Nigeria Data Protection Act 2023 and its implementing
              directive (GAID 2025). The regulator is the Nigeria Data Protection Commission
              (ndpc.gov.ng). Any organisation processing data for more than 200 Nigerian individuals
              within 6 months is generally required to register with the NDPC, appoint a data
              protection officer, and file periodic compliance reports, we expect to meet this
              threshold and will confirm our registration status here before accepting Nigerian data
              at scale. When we transfer Nigerian data across borders, we put in place the
              safeguards Nigerian law requires; we&rsquo;re finalising exactly which mechanism
              applies to our current AWS setup and will update this section once confirmed. If
              you&rsquo;re a Nigerian employer, remember that employee consent generally isn&rsquo;t
              a valid basis for routine HR processing, use contractual necessity or a legal
              obligation instead. You can also use the NDPC&rsquo;s SNAG process to resolve
              complaints with us first before involving the regulator.
            </P>
          </SubSection>

          <SubSection number="17.5" title="India.">
            <P>
              The applicable law is the Digital Personal Data Protection Act 2023 and its Rules,
              which are being rolled out in stages. The regulator is the Data Protection Board of
              India, established in late 2025. Full compliance with the Act&rsquo;s notice and
              consent requirements is required by 13 May 2027, until then, the older IT Act rules on
              sensitive personal data continue to apply. Standard HR activities like recruitment,
              onboarding, payroll, and benefits are covered by a specific employment exception and
              don&rsquo;t require separate employee consent. India doesn&rsquo;t use an
              approved-country list for international transfers, transfers are generally allowed
              unless the Indian government has specifically restricted a country, and we monitor
              that list. If you&rsquo;re an Indian employer, you remain responsible for any
              sector-specific rules that might apply to particular types of data you process.
            </P>
          </SubSection>

          <SubSection number="17.6" title="Kenya.">
            <P>
              The applicable law is the Data Protection Act 2019. The regulator is the Office of the
              Data Protection Commissioner (odpc.go.ke). We&rsquo;re registering with the ODPC both
              as a controller (for our own account data) and as a processor (for employer-customer
              employee data), these are separate registrations under Kenyan law, renewed every 24
              months. Kenyan law also requires at least one copy of certain personal data to be kept
              within Kenya; we&rsquo;re reviewing how this applies to our current setup and will
              confirm our position before accepting Kenyan data at scale. If you&rsquo;re a Kenyan
              employer, remember that an employment contract alone doesn&rsquo;t give you blanket
              permission to process all employee data, you need a specific reason for each category
              you collect. Biometric data needs explicit consent. We recommend keeping employee
              records for the length of employment plus 6 years, then deleting them securely. The
              ODPC actively enforces these rules, so please take them seriously.
            </P>
          </SubSection>
        </Section>

        <Section number={18} title="Legal Disclaimer">
          <P>
            This policy was prepared by Angle Open Source Ltd and reflects our current understanding
            of the law as of 21 July 2026. It isn&rsquo;t legal advice. If you&rsquo;re an employer
            using Open HR, we recommend getting independent legal advice in each country where you
            operate before processing employee data, especially given that India&rsquo;s rules are
            still being phased in and some details for Nigeria and Kenya are still being finalised.
          </P>
          <P>
            A few items in this policy are still being worked on: our EU representative&rsquo;s
            contact details, dedicated hosting for Nigeria, India, and Kenya, our NDPC and ODPC
            registration numbers, and confirmation of how we&rsquo;ll meet Kenya&rsquo;s local data
            storage requirement. We&rsquo;ll update this policy as each of these is resolved, and we
            won&rsquo;t make Open HR generally available in a market before the relevant legal
            requirements are in place.
          </P>
          <P>This is version 1.0, effective 21 July 2026.</P>
          <NoGapLineGroup
            lines={[
              'Angle Open Source Ltd',
              'Company number 17066367, 71–75 Shelton Street, London, England, WC2H 9JQ.',
              <MailLink key="mail" />,
            ]}
          />
        </Section>
      </Article>
    </LegalPageShell>
  )
}
