const ENDPOINTS = {
  waitlist: {
    join: () => '/waitlist',
    onboarding: () => '/waitlist/onboarding',
  },
  countries: () => '/countries',
  industries: () => '/industries',
  hiringTools: () => '/hiring-tools',
  hiringFrustrations: () => '/hiring-frustrations',
  roles: () => '/roles',
  teamSizes: () => '/team-sizes',
  auth: {
    signup: () => '/auth/signup',
    login: () => '/auth/login',
    loginOtpRequest: () => '/auth/login/otp/request',
    loginOtpVerify: () => '/auth/login/otp/verify',
    loginTotp: () => '/auth/login/totp',
    refresh: () => '/auth/refresh',
    logout: () => '/auth/logout',
    verifyEmail: () => '/auth/verify-email',
    resendVerification: () => '/auth/resend-verification',
    forgotPassword: () => '/auth/forgot-password',
    resetPassword: () => '/auth/reset-password',
    me: () => '/auth/me',
    invite: (token: string) => `/auth/invite/${token}`,
    acceptInvite: () => '/auth/accept-invite',
    totpEnroll: () => '/auth/totp/enroll',
    totpConfirm: () => '/auth/totp/confirm',
    totpDisable: () => '/auth/totp/disable',
  },
  organizations: {
    invites: () => '/organizations/invites',
  },
  jobs: {
    list: () => '/jobs',
    counts: () => '/jobs/counts',
    one: (id: string) => `/jobs/${id}`,
    /** pause, resume, close, reopen, archive, to-draft, withdraw or publish. */
    transition: (id: string, action: string) => `/jobs/${id}/${action}`,
    bulk: () => '/jobs/bulk',
    export: () => '/jobs/export',
    duplicate: (id: string) => `/jobs/${id}/duplicate`,
    details: (id: string) => `/jobs/${id}/details`,
    members: (id: string) => `/jobs/${id}/members`,
    preview: (id: string) => `/jobs/${id}/preview`,
  },
  hiring: {
    me: () => '/hiring/me',
    people: () => '/hiring/people',
    catalog: () => '/hiring/catalog',
    departments: () => '/hiring/departments',
    timezones: () => '/hiring/timezones',
    skills: () => '/hiring/skills',
    templates: () => '/hiring/templates',
    template: (id: string) => `/hiring/templates/${id}`,
    templateDuplicate: (id: string) => `/hiring/templates/${id}/duplicate`,
    templateExport: (id: string) => `/hiring/templates/${id}/export`,
  },
  onboarding: {
    profile: () => '/onboarding/profile',
    address: () => '/onboarding/address',
    addressSearch: () => '/onboarding/address/search',
    addressVerify: () => '/onboarding/address/verify',
    compliance: () => '/onboarding/compliance',
    identificationRequirements: () => '/onboarding/identification-requirements',
    business: () => '/onboarding/business',
    complete: () => '/onboarding/complete',
    status: () => '/onboarding/status',
    businessTypes: () => '/onboarding/business-types',
    companyRoles: () => '/onboarding/company-roles',
    industries: () => '/onboarding/industries',
  },
}

export { ENDPOINTS }
