const ENDPOINTS = {
  waitlist: {
    join: () => '/waitlist',
    onboarding: () => '/waitlist/onboarding',
  },
  countries: () => '/countries',
  industries: () => '/industries',
  hiringTools: () => '/hiring-tools',
  hiringFrustrations: () => '/hiring-frustrations',
  roles: () => '/roles',
  teamSizes: () => '/team-sizes',
  auth: {
    signup: () => '/auth/signup',
    login: () => '/auth/login',
    loginOtpRequest: () => '/auth/login/otp/request',
    loginOtpVerify: () => '/auth/login/otp/verify',
    loginTotp: () => '/auth/login/totp',
    refresh: () => '/auth/refresh',
    logout: () => '/auth/logout',
    verifyEmail: () => '/auth/verify-email',
    resendVerification: () => '/auth/resend-verification',
    forgotPassword: () => '/auth/forgot-password',
    resetPassword: () => '/auth/reset-password',
    me: () => '/auth/me',
    invite: (token: string) => `/auth/invite/${token}`,
    acceptInvite: () => '/auth/accept-invite',
    totpEnroll: () => '/auth/totp/enroll',
    totpConfirm: () => '/auth/totp/confirm',
    totpDisable: () => '/auth/totp/disable',
  },
  organizations: {
    invites: () => '/organizations/invites',
  },
  onboarding: {
    profile: () => '/onboarding/profile',
    address: () => '/onboarding/address',
    addressSearch: () => '/onboarding/address/search',
    addressVerify: () => '/onboarding/address/verify',
    compliance: () => '/onboarding/compliance',
    identificationRequirements: () => '/onboarding/identification-requirements',
    business: () => '/onboarding/business',
    complete: () => '/onboarding/complete',
    status: () => '/onboarding/status',
    businessTypes: () => '/onboarding/business-types',
    companyRoles: () => '/onboarding/company-roles',
    industries: () => '/onboarding/industries',
  },
}

export { ENDPOINTS }
