import type { Job, JobManager } from './types'

/**
 * Stand-in job data. There are no jobs endpoints yet, so `requests.getJobs`
 * resolves with this list; swapping in the real API means changing that one
 * function and deleting this file.
 *
 * The open, paused, draft and closed rows mirror the Figma list frame
 * (8440:566108) one for one, so the built page can be measured against it.
 */

const MANAGERS = {
  alice: { name: 'Alice', colour: 'green' },
  bob: { name: 'Bob', colour: 'yellow' },
  charlie: { name: 'Charlie', colour: 'aqua' },
  diana: { name: 'Diana', colour: 'red' },
  fiona: { name: 'Fiona', colour: 'purple' },
  isabella: { name: 'Isabella', colour: 'orange' },
  jerry: { name: 'Jerry', colour: 'fuchsia' },
  lucas: { name: 'Lucas', colour: 'blue' },
  oluwasegun: { name: 'Oluwasegun', colour: 'teal' },
  owen: { name: 'Owen', colour: 'grey' },
} satisfies Record<string, JobManager>

// Creator is not part of the design's table, so each fixture is created by its
// manager.
const JOB_FIXTURES: Job[] = (
  [
    {
      id: 'job-001',
      title: 'Marketing Specialist',
      department: 'Marketing',
      employmentType: 'Contract',
      location: 'UK',
      workplace: 'Hybrid',
      status: 'open',
      manager: MANAGERS.jerry,
      totalApplicants: 27,
      newApplicants: 6,
      postedAt: '2026-11-01',
    },
    {
      id: 'job-002',
      title: 'Data Analyst',
      department: 'Analysis',
      employmentType: 'Part-time',
      location: 'Ireland',
      workplace: 'Remote',
      status: 'open',
      manager: MANAGERS.oluwasegun,
      totalApplicants: 29,
      newApplicants: 4,
      postedAt: '2026-10-15',
    },
    {
      id: 'job-003',
      title: 'Data Analyst',
      department: 'Analysis',
      employmentType: 'Part-time',
      location: 'Scotland',
      workplace: 'Remote',
      status: 'open',
      manager: MANAGERS.fiona,
      totalApplicants: 29,
      newApplicants: 4,
      postedAt: '2026-10-15',
    },
    {
      id: 'job-004',
      title: 'Product Designer',
      department: 'Design',
      employmentType: 'Full-time',
      location: 'USA',
      workplace: 'Remote',
      status: 'paused',
      manager: MANAGERS.alice,
      totalApplicants: 30,
      newApplicants: 7,
      postedAt: '2026-10-15',
    },
    {
      id: 'job-005',
      title: 'Software Engineer',
      department: 'Development',
      employmentType: 'Contract',
      location: 'Canada',
      workplace: 'On-site',
      status: 'paused',
      manager: MANAGERS.bob,
      totalApplicants: 5,
      newApplicants: 3,
      postedAt: '2026-09-22',
    },
    {
      id: 'job-006',
      title: 'Data Analyst',
      department: 'Analytics',
      employmentType: 'Part-time',
      location: 'Australia',
      workplace: 'Hybrid',
      status: 'paused',
      manager: MANAGERS.charlie,
      totalApplicants: 12,
      newApplicants: 8,
      postedAt: '2026-08-10',
    },
    {
      id: 'job-007',
      title: 'Product Manager',
      department: 'Management',
      employmentType: 'Full-time',
      location: 'US',
      workplace: 'Hybrid',
      status: 'paused',
      manager: MANAGERS.charlie,
      totalApplicants: 5,
      newApplicants: 3,
      postedAt: '2026-07-12',
    },
    {
      id: 'job-008',
      title: 'Data Analyst',
      department: 'Analytics',
      employmentType: 'Contract',
      location: 'Australia',
      workplace: 'On-site',
      status: 'draft',
      manager: MANAGERS.owen,
      totalApplicants: 6,
      newApplicants: 4,
      postedAt: '2026-02-14',
    },
    {
      id: 'job-009',
      title: 'Frontend Developer',
      department: 'Development',
      employmentType: 'Full-time',
      location: 'Germany',
      workplace: 'Remote',
      status: 'closed',
      manager: MANAGERS.owen,
      totalApplicants: 5,
      newApplicants: 2,
      postedAt: '2026-01-09',
    },
    {
      id: 'job-010',
      title: 'Content Strategist',
      department: 'Marketing',
      employmentType: 'Part-time',
      location: 'France',
      workplace: 'Hybrid',
      status: 'closed',
      manager: MANAGERS.owen,
      totalApplicants: 4,
      newApplicants: 3,
      postedAt: '2025-11-30',
    },
    {
      id: 'job-011',
      title: 'Software Engineer',
      department: 'Engineering',
      employmentType: 'Full-time',
      location: 'Italy',
      workplace: 'On-site',
      status: 'closed',
      manager: MANAGERS.lucas,
      totalApplicants: 7,
      newApplicants: 1,
      postedAt: '2025-09-18',
    },
    {
      id: 'job-012',
      title: 'SEO Specialist',
      department: 'Marketing',
      employmentType: 'Part-time',
      location: 'Spain',
      workplace: 'Remote',
      status: 'closed',
      manager: MANAGERS.lucas,
      totalApplicants: 4,
      newApplicants: 2,
      postedAt: '2025-08-05',
    },
    {
      id: 'job-013',
      title: 'Graphic Designer',
      department: 'Design',
      employmentType: 'Part-time',
      location: 'Sweden',
      workplace: 'Remote',
      status: 'closed',
      manager: MANAGERS.lucas,
      totalApplicants: 3,
      newApplicants: 4,
      postedAt: '2025-05-12',
    },
    {
      id: 'job-014',
      title: 'Graphic Designer',
      department: 'Design',
      employmentType: 'Part-time',
      location: 'Sweden',
      workplace: 'Remote',
      status: 'closed',
      manager: MANAGERS.lucas,
      totalApplicants: 3,
      newApplicants: 4,
      postedAt: '2025-05-12',
    },
    {
      id: 'job-015',
      title: 'Business Analyst',
      department: 'Analytics',
      employmentType: 'Full-time',
      location: 'Norway',
      workplace: 'On-site',
      status: 'closed',
      manager: MANAGERS.lucas,
      totalApplicants: 5,
      newApplicants: 2,
      postedAt: '2025-04-24',
    },
    {
      id: 'job-016',
      title: 'System Administrator',
      department: 'IT Support',
      employmentType: 'Full-time',
      location: 'Belgium',
      workplace: 'Remote',
      status: 'closed',
      manager: MANAGERS.lucas,
      totalApplicants: 6,
      newApplicants: 3,
      postedAt: '2025-03-16',
    },
    {
      id: 'job-017',
      title: 'Mobile Developer',
      department: 'Development',
      employmentType: 'Contract',
      location: 'Finland',
      workplace: 'Hybrid',
      status: 'closed',
      manager: MANAGERS.isabella,
      totalApplicants: 5,
      newApplicants: 1,
      postedAt: '2023-02-11',
    },
    {
      id: 'job-018',
      title: 'Copywriter',
      department: 'Content',
      employmentType: 'Part-time',
      location: 'Ireland',
      workplace: 'Remote',
      status: 'closed',
      manager: MANAGERS.isabella,
      totalApplicants: 4,
      newApplicants: 2,
      postedAt: '2023-01-08',
    },
    {
      id: 'job-019',
      title: 'Project Manager',
      department: 'Management',
      employmentType: 'Full-time',
      location: 'Germany',
      workplace: 'On-site',
      status: 'archived',
      manager: MANAGERS.charlie,
      totalApplicants: 40,
      newApplicants: 16,
      postedAt: '2025-02-10',
    },
    {
      id: 'job-020',
      title: 'Data Scientist',
      department: 'Data Analysis',
      employmentType: 'Part-time',
      location: 'Australia',
      workplace: 'Remote',
      status: 'archived',
      manager: MANAGERS.bob,
      totalApplicants: 25,
      newApplicants: 10,
      postedAt: '2025-01-28',
    },
    {
      id: 'job-021',
      title: 'Digital Marketing Specialist',
      department: 'Marketing',
      employmentType: 'Full-time',
      location: 'France',
      workplace: 'Remote',
      status: 'expired',
      manager: MANAGERS.diana,
      totalApplicants: 32,
      newApplicants: 4,
      postedAt: '2025-01-14',
    },
  ] satisfies Omit<Job, 'createdBy'>[]
).map((job) => ({ ...job, createdBy: job.manager }))

export { JOB_FIXTURES }
